MODEL:
  FLOW_COUPLING: "additive"
  FLOW_DROPOUT: 0.2
  FLOW_BATCH_NORM: False
  NUM_SAMPLES: 10
  MODEL_POSE: False
  MODEL_GLOB_ROT: False
  MODEL_CAM: False
  MODEL_SHAPE: False
LOSS:
  KP2D_WEIGHT: 1000.0
  PARAM_NLL_WEIGHT: 1.0
DATASET:
  CROP_PROB: 0.25
  CROP_FACTOR: [0.0, 0.3]
  EXTREME_CROP_PROB: 0.8
  EXTREME_CROP_LEVEL: 1
TRAIN:
  LR: 5e-5