MODEL:
  FLOW_COUPLING: "rq_spline"
  FLOW_SPLINE_NUM_BINS: 20
  FLOW_SPLINE_TAIL_BOUND: 6.0
  FLOW_NUM_LAYERS: 16
  FLOW_HIDDEN_FEATURES: 1024
  FLOW_DROPOUT: 0.2
  FLOW_BATCH_NORM: False
  FLOW_BASE_STD: 0.7
  NUM_SAMPLES: 10
  MODEL_POSE: False
  MODEL_GLOB_ROT: False
  MODEL_CAM: False
LOSS:
  KP2D_WEIGHT: 1000.0
  PARAM_NLL_WEIGHT: 1.0
DATASET:
  CROP_PROB: 0.25
  CROP_FACTOR: [0.0, 0.3]
  EXTREME_CROP_PROB: 0.8
  EXTREME_CROP_LEVEL: 1
