MODEL:
  FLOW_COUPLING: "additive"
  FLOW_NUM_LAYERS: 8
  FLOW_DROPOUT: 0.5
  FLOW_BATCH_NORM: False
  DECODER:
    LORA_R: 16
    LORA_ALPHA: 32
LOSS:
  KP2D_WEIGHT: 1000.0
  PARAM_NLL_WEIGHT: 1.
DATASET:
  CROP_PROB: 0.25
  CROP_FACTOR: [0.1, 0.2]
  EXTREME_CROP_PROB: 0.5
  EXTREME_CROP_LEVEL: 1
